name:          SAU/CAL Engineering Best Practices
title:         SAU/CAL Engineering Best Practices
description:   Project engineering best practices used by SAU/CAL.
url:           https://saucal.github.io/
baseurl:       /Engineering-Best-Practices
author:
  name:    SAU/CAL
  email:   info@saucal.com
  github:  saucal
  twitter: saucal

markdown:      kramdown
permalink:     pretty
highlighter:   rouge
encoding:      utf-8
kramdown:
  input: GFM
sass:
  sass_dir: _includes/_sass
